### ISSUE TITLE
PLP: Total of products does not match the total on the Filter facet

### ISSUE THREAD

**Issue by szcoleman** [hlxsites/eecol#111]
The total of products does not match the total on the Filter facet

Steps
1) Go to any product list page 
https://main--eecol--hlxsites.helix3.dev/ca/en/products/category/ec-safety-ppe-and-workwear/ec-locks/ec-lockout-tagout
2) Filter any product category or product attribute
expected: the number of product in the facet filter should match the actually total product
actual: total products is not matching the total

![image](https://user-images.githubusercontent.com/100615096/204371907-4008b4da-66f8-472a-bd65-22ca74aac8df.png)

**Comment by dylandepass** [comment]
@szcoleman I noticed that this is not a feature of the current eecol site. Only sub categories have totals. Is this required?

**Comment by dylandepass** [comment]
This was removed in #113, if it needs to be there than please reopen and assign to me.

**Comment by rsfierst** [comment]
1. the facets are not meant to show counts
2. the facet counts are not supposed to add up to the total number of products
