### ISSUE TITLE
duplicate ids for inputs on signin page

### ISSUE THREAD

**Issue by maxakuru** [hlxsites/eecol#61]
id `email` is used for both signin and beta-signin form inputs

ref: https://main--eecol--hlxsites.hlx.live/ca/en/signin

**Comment by wesco-abhinaydonadula** [comment]
@wesco-LalithChaganti please test this and let me know if you still see any duplicate id's on the login page, thanks.

cc @chase-cox

**Comment by wesco-LalithChaganti** [comment]
> @wesco-LalithChaganti please test this and let me know if you still see any duplicate id's on the login page, thanks.
> 
> cc @chase-cox

@maxakuru : am able to see the unique id's but not able to login with AXE001us+TA1@gmail.com.

**Comment by wesco-abhinaydonadula** [comment]
@wesco-LalithChaganti Thank you for looking at it and confirming that no duplicate id's are on the login page.

The login issue is out of scope for this bug, please refer it in it's own bug, thanks.
