### ISSUE TITLE
view cart button is not displayed any text when user clicks on cart.

### ISSUE THREAD

**Issue by wesco-LalithChaganti** [hlxsites/eecol#65]
view cart button is not displayed when user clicks on cart
![image](https://user-images.githubusercontent.com/113196733/201140552-d948d6a5-8c59-4dd3-8676-8f3cd9fd29d1.png)

**Comment by wesco-LalithChaganti** [comment]
<a class="button secondary" href="/ca/en/cart-details"> </a> 

no text is mentioned in Dom

**Comment by MillyCMM** [comment]
@wesco-LalithChaganti - Please reference/ link issue you tested.

**Comment by maxakuru** [comment]
fixed alongside #70 
this was a missing placeholder (`viewCart`) in `/ca/en/placeholders`
