### ISSUE TITLE
Bug:Error 404 Unsupported characters in path is displayed when user clicks on sku from Cart Page

### ISSUE THREAD

**Issue by wesco-LalithChaganti** [hlxsites/eecol#67]
Bug: The below Erorr Page is displayed When user clicks on Product from CheckOut page

Steps to Reproduce:
1. Login to the application[axe001us+e2e2@gmail.com]
2. Click on Cart
3. Clicks on any Product

Error 404 Unsupported characters in path
Unsupported characters in path

Error 54113
Details: cache-iad-kiad7000088-IAD 1668096846 3972820485

**Comment by maxakuru** [comment]
this should be fixed, related to #69
