### ISSUE TITLE
Bug: Empty Page is displayed when user clicks on Checkout button

### ISSUE THREAD

**Issue by wesco-LalithChaganti** [hlxsites/eecol#68]
Bug: Empty Page is displayed when user clicks on Checkout button

Steps

![image](https://user-images.githubusercontent.com/113196733/201153539-b3512a02-bcb7-403e-b5ca-6130c6489006.png)

**Comment by maxakuru** [comment]
@wesco-LalithChaganti this should be fixed now, if it's still happening try clearing cache
if it's still happening after that, feel free to reopen
