### ISSUE TITLE
Search Linked to SOLR Fusion

### ISSUE THREAD

**Issue by dbursicwesco** [hlxsites/eecol#72]
this can be up for some discussion if you're ready to have it, but rather than build existing search in 1A, knowing its throwaway very quickly, wouldn't we attempt fusion? Endpoints are available.

**Comment by maxakuru** [comment]
closing in favor of https://github.com/hlxsites/eecol-cloudflare-worker/issues/34

UI is already hooked up to search & suggestions so this would be a strictly backend/worker change.. we can talk about when and how we implement in that issue
