### ISSUE TITLE
Cannot log in

### ISSUE THREAD

**Issue by rsfierst** [hlxsites/eecol#78]
1. Navigate to https://main--eecol--hlxsites.hlx.live/ca/en/signin
2. provide name/password
3. click Login to Beta
4. Login page just sits there.  Behind the scenes this endpoint returns a 404 error :  https://main--eecol--hlxsites.hlx.live/api/auth/signin

**Comment by maxakuru** [comment]
just for info sharing..
this is because .live is not a worker url and we're still using paths assuming we're on the worker in some places

for example, sign in: https://github.com/hlxsites/eecol/blob/main/scripts/modules/Auth.js#L135
should be `${this.store.upstreamURL}/api/auth/signin`

**Comment by maxakuru** [comment]
@rsfierst my bad, turns out this isn't just the href.. 

it's due to the change in #77 that resulted in a different payload than we expected
fixed it quick since OrderHistory depends on a session and working on that now

fix in #81
